### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by jverzani** [dpsanders/ValidatedNumerics.jl#10]
Hi @dpsanders . Would it be possible to tag a new version of this package to reflect the changes on master from the released one?

**Comment by dpsanders** [comment]
Hi,
Thanks for the suggestion. There are currently some things semi-broken and I was waiting for those to be fixed before tagging. However, it's been a while since we've worked on the package and I'm happy to tag a new minor version in the mean time. Let me look at it tomorrow and see if I can do some semi-fixes, then I'll tag it.

I'd be happy to have suggestions about features etc. that you'd be interested in, and your use case.

**Comment by jverzani** [comment]
Hi, I am using it for a little project to draw implicit equations: https://github.com/jverzani/ImplicitEquations.jl. It seemed exactly what was needed for that. As for suggestions, I'm not sure these are right or necessary, but at the top of this file https://github.com/jverzani/ImplicitEquations.jl/blob/master/src/intervals.jl I added some methods.

Thanks!

**Comment by dpsanders** [comment]
That looks like a very nice package (and not so "little"!).
I decided that the easiest thing to do was to tag a new version (0.0.3) and then go to work on it. I've just sent the request to update the published version to current master.

**Comment by dpsanders** [comment]
We are working hard on the package and will tag an improved version soon...

**Comment by dpsanders** [comment]
Closing, since a version was tagged. Hope to release v0.1 soon.
