### ISSUE TITLE
Using ± in construction of intervals ignores @bigintervals

### ISSUE THREAD

**Issue by gmoutsin** [dpsanders/ValidatedNumerics.jl#172]
Writing

`@biginterval(1)±1`

returns

`[-0, 2]`

Which is of type `ValidatedNumerics.Interval{Float64}` instead of `ValidatedNumerics.Interval{BigFloat}` that is should be.

**Comment by gmoutsin** [comment]
Setting the precision with `setprecision(Interval, 256)` works though.

**Comment by dpsanders** [comment]
Thanks, this is a problem with the definition of `..`, which is currently used in `±`.
This, in turn, calls `@interval(a-b, a+b)`, which has the same problem, since `@interval` checks the global precision mode to see which kind of `Interval` to make. 

Solving the problem with `@interval` may be difficult; solving `..` and `±` should be easy.

**Comment by lbenet** [comment]
Closing this; solved by #209

**Comment by dpsanders** [comment]
Looking at this again, I don't think it makes very much sense to use `±` with interval arguments.

**Comment by gmoutsin** [comment]
I did find it convenient to use as I had the value and the numerical error separately.
