### ISSUE TITLE
bisect fails for infinite interval

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#243]
```jl
julia> x = y = -∞..∞
[-∞, ∞]

julia> X = x × y
[-∞, ∞] × [-∞, ∞]

julia> bisect(X)
([NaN, NaN] × [-∞, ∞],[NaN, NaN] × [-∞, ∞])
```

Although it's not clear that this is actually a useful thing to do.

**Comment by dpsanders** [comment]
Nor is it clear what the correct bisection of a semi-infinite interval would mean. Maybe just throw an error? 

An alternative is to have a way to just shave off infinity from the interval to leave a finite one.

**Comment by dpsanders** [comment]
Nor is it clear what the correct bisection of a semi-infinite interval would mean. Maybe just throw an error? 

An alternative is to have a way to just shave off infinity from the interval to leave a finite one.

**Comment by lbenet** [comment]
I think the reason bisect fails is because it does not check if the interval is unbounded or empty; see `mid` for reference. 

As a side remark, I just noticed that in the standard table 10.2 (page 39) states that `mid` is *defined* as "no value" for an empty or unbounded interval. Yet, in page 64 it states that for the interval `[-∞, ∞]` it should return 0 (as we do), but for intervals like `[-∞,x]` with finite `x` it should return the "finite largest T number of largest maginitude", i.e., `nextfloat(-Inf)`, and something alike for `[x,∞]`; we don't follow this, and i think there is no test in the ITF1788 suite that checks this.

**Comment by dpsanders** [comment]
Yes, you're right. I'll change it.
